### ISSUE TITLE
Consider removing property setters from non-Draft API objects

### ISSUE THREAD

**Issue by nkuehn** [sphereio/commercetools-php-sdk#114]
They suggest that the Object can be modified and then POST/PUT ed as changed to the API, but in fact changes can only be done via Update Actions. 

-> may break stuff (tests...). 

Just mark internal?

**Comment by nkuehn** [comment]
Problem: The sub-Objects like Money, etc. pp. are re-used massively across draft and API response objects.   To consistently make the API responses not look like they should be changed we would have to remove setters on all sub-objects, too.   
But that's a larger effort with massive duplication. 

-> later.

**Comment by jayS-de** [comment]
Will not be done with the actual design
