### ISSUE TITLE
Consider providing an encypted cookie PHP Session implementation

### ISSUE THREAD

**Issue by nkuehn** [sphereio/commercetools-php-sdk#118]
sphere is proposing stateless frontends very strongly, but there are practical reasons for session data (e.g. logged in status, current items in cart etc. ). 

The sphere java frontends use encrypted cookies, which is a stable feature in Play Framework, but there seems to be no "authoritative" implementation for PHP and the discussion about it is on a confusingly low level unfortunately.  We could take the Play Framework crypto logic as a template. 

Stuff to consider / options / input
 * http://suhosin.org/stories/configuration.html#suhosin-cookie-encrypt
 * http://dev.af83.com/2010/02/15/encrypted-session-cookies-in-php.html
 * https://www.marcus-povey.co.uk/2013/03/18/encrypted-client-side-php-sessions/
 * lots of qualified and not so qualified stuff on stackoverflow

could be a separate repo, too.

**Comment by jayS-de** [comment]
Will not be provided by the SDK. As frameworks implement the cookie and session handling different
