### ISSUE TITLE
Integration / System tests against  live SPHERE API

### ISSUE THREAD

**Issue by nkuehn** [sphereio/commercetools-php-sdk#13]
functional depth can be discussed for the M2 release, but the general setup should be there and do full-trip calls including OAuth, Typed response models etc. 

Must run on Travis, too, so we probably must create encrypted variables again etc.

**Comment by schleichardt** [comment]
@ct-jensschulze @nkuehn  If you need help, you can ask me.

**Comment by nkuehn** [comment]
yes we will! (need help and will ask)

**Comment by nkuehn** [comment]
(can be moved to next milestone as necessary as long as they're done for the RC release)

**Comment by nkuehn** [comment]
We also have to clarify whether they are mandatory in the local test run or whether it's enough to have them in the CI configuration.

**Comment by ct-jensschulze** [comment]
it's sufficient to run the integration tests on the CI system. But the tests can be run anytime on a local environment

**Comment by nkuehn** [comment]
@ct-jensschulze the issue came up because ant tried to run them when I just called "ant" without parameters (that's the way the README asks to do it).  that's because the integration tests are part of the "phpunit"  target, which does not make sense to me as they are integration tests and not unit tests. 

maybe refactor the target names a bit?    rather prepare / build / analyze / test-unit / test-integration / generate-docs   or such.
