### ISSUE TITLE
rename the repository to commercetools-php-sdk, too? 

### ISSUE THREAD

**Issue by nkuehn** [sphereio/commercetools-php-sdk#137]
@hajoeichler we're going to push in another RC just for the renaming now to not lose time until users can test the SDK.  

we should decide whether to rename the repository right now.

**Comment by ct-jensschulze** [comment]
Should not be renamed, we should create a new one. So i could abandon the sphere-php-sdk but it's still possible to read all the old versions.

And the new one would be registered at packagist with the new url and namespace

**Comment by nkuehn** [comment]
you'll have to explain the packagist issue to me. Sure we will start from scratch at packagist, but what has that to do with the old versions?  Why would packagist want to delete the old package site just because the package has a new name from a certain version on (the repo remains accessible as a redirect and git repos don't have a "baked in" name afaik). 

I find it _extremely_ unattractive to not have the github redirects,  have to re-write all Issues, etc. pp.

**Comment by nkuehn** [comment]
P.S.:  in any case, we'll have to do some kind of "end of package name life" tag that has a composer description that contains very strong language to now use the new package name.  Best do that before tagging the new one.
