### ISSUE TITLE
Expansion trait for ProductProjectionSearchRequest ?

### ISSUE THREAD

**Issue by vancromp** [sphereio/commercetools-php-sdk#144]
Hello,

I'm wondering if the expansion trait is missing in ProductProjectionSearchRequest (https://github.com/sphereio/commercetools-php-sdk/blob/develop/src/Request/Products/ProductProjectionSearchRequest.php#L34).
When I add it, expansion works for this kind of request.

Have a good day.

Pierre

**Comment by nkuehn** [comment]
Good timing :-) 
Reference expansion has been added to the platform API just on 29.07.2015 ( http://dev.sphere.io/release-notes.html ), so it's not in the SDK yet. 

we'll add it in the coming releases.
