### ISSUE TITLE
Serialization of Closure is not allowed

### ISSUE THREAD

**Issue by CHH** [sphereio/commercetools-php-sdk#157]
I’m using Symfony Security and it would be nice if the customer model could be serialized. Right now when I try to serialize a customer model I get the error "Serialization of Closure is not allowed" from the serialize() function.

**Comment by ct-jensschulze** [comment]
Try to serialize the object as Array with the toArray() method. Und unserialize it using 

$customerSerialized = serialize($customer->toArray());
Customer::fromArray(unserialize($customerSerialized));
