### ISSUE TITLE
PaymentInfo does not exist and could not be loaded

### ISSUE THREAD

**Issue by chuykov** [sphereio/commercetools-php-sdk#158]
According to the following documentation [Order](http://sphereio.github.io/commercetools-php-sdk/docs/master/class-Commercetools.Core.Model.Order.Order.html) , I try to call method:
```
$paymentInfo = $payment->getPaymentInfo();
```
I suppose that $paymentInfo it is instance of [PaymentInfo](http://sphereio.github.io/commercetools-php-sdk/docs/master/class-Commercetools.Core.Model.Payment.PaymentInfo.html) , however I get a weird error:
> Warning: class_implements(): Class \Commercetools\Core\Model\Cart\PaymentInfo does not exist and could not be loaded in vendor/commercetools/php-sdk/src/Model/Common/AbstractJsonDeserializeObject.php on line 62

Could you please advise what I'm doing wrong?

Maybe in the [commit](https://github.com/sphereio/commercetools-php-sdk/commit/c156560fbf2b118d8228512f00580a8eb6ae3a3e) src/Model/Order/Order.php instead of:
```
class Order extends Resource
{
	public function fieldDefinitions()
	{
		return [
			'paymentInfo' => [static::TYPE => '\Commercetools\Core\Model\Cart\PaymentInfo']
		];
	}
}
```
there should be something like the following:
```
class Order extends Resource
{
	public function fieldDefinitions()
	{
		return [
			'paymentInfo' => [static::TYPE => '\Commercetools\Core\Model\Payment\PaymentInfo']
		];
	}
}
```
Could you please tell what is your idea on this?

**Comment by ct-jensschulze** [comment]
You are right. Just hotfixed it and tagged it as RC6.

Thanks! :+1:
