### ISSUE TITLE
Cant get value back from customFieldObject

### ISSUE THREAD

**Issue by steffanhalv** [sphereio/commercetools-php-sdk#172]
Cant get value back from customfieldobject

```
$customFieldObject = new CustomFieldObject();
$customFieldObject->setFields(
    FieldContainer::of()
        ->set("field", "value")
);

$value = $customFieldObject->getFields()->fieldDefinition("field"); //should return "value" but instead returns null
```

**Comment by jayS-de** [comment]
To get the desired value it should be:

```
$value = $customFieldObject->getFields()->get("field"); 
$value = $customFieldObject->getFields()->getField(); 
```

With the SDK it's not possible to generate the models based on your project definition, so we can't provide the Getters for a specific field which has been created using the API. This is only knowledge you have.

 But you should not create a CustomFieldObject with the code. Normally you should create a Draft-Object to create an Resource using the API. And then query the object. The JsonObject-Mapper ```$request->mapResponse($response) or $response->toObject()``` should give you the correct object which has been returned by the API.

Btw when you expanded the ```custom.type``` reference, the object mapper will also give you the correct type for your field.

**Comment by steffanhalv** [comment]
Thanks I found there was a typo in my code when I tried $channel->getCustom()->getFields()->get("field"). Now it works :)

**Comment by steffanhalv** [comment]
Just a small thing, is it correct that $customFieldObject->getFields()->get("field"); should be marked with @internal ?

**Comment by jayS-de** [comment]
Yes. The ```get``` is an internal function of the JsonObject. And getters should not have a Parameter. So it would be better to use the getField() method.

**Comment by steffanhalv** [comment]
I did just update to the latest dev-master with composer, but cant find any getField() function

**Comment by jayS-de** [comment]
Yes. You can't field it. When you use the method getField the __call function of the JsonObject will be executed. The __call method tries first to validate if you use a getter or setter, and that the field exists in your object. Then it will call get("<fieldName>") internally.

**Comment by steffanhalv** [comment]
Yes but what I mean is that the method is not there. :)

**Comment by jayS-de** [comment]
Just try it out:

```
$customFieldObject = new CustomFieldObject();
$customFieldObject->setFields(
    FieldContainer::of()
        ->set("field", "value")
);

$value = $customFieldObject->getFields()->getField();
var_dump($value);
$value = $customFieldObject->getFields()->get("field");
var_dump($value);
```

It works. Thats what i meant, that the SDK can't know about fields you created with the API. The SDK gives you the tools to access the fields, but don't know if they really exists. So I can't generate stubs or annotations that the IDE can shows their existence.

**Comment by steffanhalv** [comment]
Ah ok, now I understand. Thx!
