### ISSUE TITLE
Cart::getLineItemCount should not use getQuantity to calculate item counts

### ISSUE THREAD

**Issue by Haehnchen** [sphereio/commercetools-php-sdk#233]
instead of collecting quantity for all cart items inside `Cart::getLineItemCount`, i would expect to get article count of basket.
bahvoir should be like a"mini basket", which provides article count instead of an overall quantity count.

**Comment by jayS-de** [comment]
Actually it's very easy to get the article count by just using Cart::getLineItems::count(). The reason for the helper function was, that most of the time a mini basket shows the number of ordered items and not of ordered articles.
