### ISSUE TITLE
Missing version in CustomObjectDraft

### ISSUE THREAD

**Issue by Haehnchen** [sphereio/commercetools-php-sdk#249]
>  the new value and the version is incremented. The version control is optional. If the request contains a version and an objec

https://github.com/sphereio/commercetools-php-sdk/blob/develop/src/Model/CustomObject/CustomObjectDraft.php

**Comment by jayS-de** [comment]
fix the issue and also change the CustomObjectCreateRequest to accept custom object drafts as well as custom objects. preparing the release of v1.3.1 atm

**Comment by Haehnchen** [comment]
thx! ;)

**Comment by jayS-de** [comment]
v1.3.1 released: https://github.com/sphereio/commercetools-php-sdk/releases/tag/v1.3.1
