### ISSUE TITLE
New asset api not included in sdk

### ISSUE THREAD

**Issue by Haehnchen** [sphereio/commercetools-php-sdk#252]
Newly added asset api feature is not included in this sdk. https://dev.commercetools.com/http-api-types.html#asset. They are inside Products, Variants and ProductVariants (Order).

**Comment by jayS-de** [comment]
They are supported with v1.3. Plesse take a look in the changelog and #243

If something is missing please let me know.

**Comment by Haehnchen** [comment]
thanks we just implemented it synchronously. will remove our workaround after updating to latest sdk version
