### ISSUE TITLE
Harmonization of the CustomObjectCreateRequest API

### ISSUE THREAD

**Issue by b3nl** [sphereio/commercetools-php-sdk#258]
Usually you use the *::ofDraft API to get create requests. But the custom objects creation is the only create request, where you use ofObject. I would suggest, that you add an ofDraft too, to make life easier and more expectable.

**Comment by jayS-de** [comment]
I will add a ofDraft method, which just accepts a DraftObject. The reason for the ofObject was that I initially didn't had a CustomObjectDraft and the CustomObject-Endpoint behaves a little different then the other API endpoints
