### ISSUE TITLE
maybe a separate "best practices" package with implemented use cases

### ISSUE THREAD

**Issue by nkuehn** [sphereio/commercetools-php-sdk#36]
Would it be a good Idea to provide a kind of "add on" package to the SDK that contains higher-level best practice code for typical use cases in a shopfront?  Should be a separate Repo with own versioning.

e.g.  a request that gets the cart for the final step in the checkout (you have to send a cart recalculate update request with reference expansion of the products and use the returned cart for display).  Or a template request Object that creates a Cart that is configured to be usable as a user whishlist.   etc. pp. 

Stupid Idea?

**Comment by CHH** [comment]
Moltin does that in a similar way, they have packages separate from the SDK, e.g. for building a Cart:

https://github.com/moltin/cart

**Comment by jayS-de** [comment]
Will be provided with https://github.com/sphereio/commercetools-php-symfony
