### ISSUE TITLE
Provide version information of php sdk in user agent header

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/commercetools-php-sdk#62]
currently we receive `Guzzle/5.2.0 curl/7.35.0 PHP/5.5.9-1ubuntu4.9`.
It would be nice to get `sphere-php-sdk 1.0 M2` or a like.

**Comment by nkuehn** [comment]
Is already implemented, but I have a proposal for improvement:  To make the creation of Kibana Dashboards easier, we could agree on two special SDK headers in addition to the standard User-Agent:  "SDK" and "SDK-Version".  So segmentations over SDKs and their versions wouldn't require custom string splitting in Kibana. 

@schleichardt @onibox what do you think?

**Comment by schleichardt** [comment]
It it is no problem to add additional header fields.

**Comment by nkuehn** [comment]
will do new one.
