### ISSUE TITLE
Handle X-Correlation-ID header

### ISSUE THREAD

**Issue by svenmueller** [sphereio/commercetools-php-sdk#69]
SPHERE.IO API response contains a header called `X-Correlation-ID`. This header should also be used when handling events (e.g. warning, errors etc.).

**Comment by nkuehn** [comment]
Hi Sven, I can't find this Header in the API documentation.  
Current practice is that the SDKs should not implement undocumented functionality. 
Is it planned to make this header official?

**Comment by nkuehn** [comment]
@schleichardt  @ct-jensschulze @hajoeichler  What's your opinion on this (SDK support for an undocumented but helpful header)

**Comment by mmoelli** [comment]
@nkuehn it's not undocumented: http://dev.sphere.io/http-api-contract.html#deprecation

**Comment by nkuehn** [comment]
@mmoelli  this is about X-Correlation-ID, not about X-Deprecation-Notice

**Comment by mmoelli** [comment]
Ah, sorry. My bad..

**Comment by nkuehn** [comment]
@mmoelli  but do you have an opinion?

**Comment by mmoelli** [comment]
This would only makes sense if we can use them for investigating. I think this will be possible. So I guess this would help the devs indeed.

**Comment by nkuehn** [comment]
I have set this to BACKLOG now.  Please ping here once we are able to answer support requests based on a correlation ID.  
Once that process is in place, the SDK should print out the correlation ID with Error Messages and ask the user to include the correlation ID when contacting SPHERE, e.g.:
"If getting in contact with SPHERE.IO about this error, please include the following Correlation ID: 11111111111111"
